### ISSUE TITLE
[new page] /now

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/oolong#1]
## page details
**title:** now
**url:** /now

## page content
this page should be about [what i'm doing right now](https://nownownow.com/about), inspired by [derek sivers](https://sive.rs/now).

it should include:
- [x] explanation & link to [nownownow](https://nownownow.com/about)
- [x] date / time it was last updated
- [x] brief bio — living in bk with my cat, working at lickability, etc
- [x] a list of media i'm into right now — games i'm playing, books i'm reading, tv shows i'm watching, music i'm listening to
  - [x] embedded spotify playlist
- [x] link to mastodon
- [x] link to jillian.garden
- [x] explanation of this project, since this is what i'm currently working on!

## tasks
- [x] add page to /src
- [x] decide what content should go on the page
- [x] figure out basic page layout
- [x] write & add draft content
