### ISSUE TITLE
[new collection] games

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/oolong#10]
## collection details
a collection of games i'm playing, have played, or want to play.

**collection name:** games
**collection properties:**
- tags: game
- game details
  - title
  - cover
  - url (link to steam if applicable)
  - game uid (if applicable)
- status
  - want to play
  - playing
  - playing / ongoing
  - finished playing
  - shelved
- rating (just use emoji for now, might use stars later)
- notes (md body copy)

## tasks
- [x] make a **/games/** folder
- [ ] make a **game.md** layout with the above properties in the front matter
- [x] add a few games i'm currently playing to the collection

**Comment by jilliangmeehan** [comment]
didn't end up making a layout for this since i'm not sure it makes a ton of sense yet. also edited the properties a bit for simplicity's sake.
