### ISSUE TITLE
[new page] changelog

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/oolong#2]
## page details
**title:** changelog
**url:** /log

## page content
i want to have a log on the site — sort of like [this one](https://xandra.cc/updates) — to keep track of what changes i've made.

it should have:
- [x] a list of updates
  - [x] each update should have the date & time of the update
  - [x] each update should have some text
- [x] updates should be sorted reverse-chron, so the latest are at the top

## tasks
- [x] add page to /src
- [x] decide what content should go on the page
- [x] figure out basic page layout
- [x] write & add draft content
