### ISSUE TITLE
[new page] home

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/oolong#3]
## page details
**title:** home
**url:** /index

## page content
this is the home page, obviously. i think it will probably end up changing a lot over the course of this project, because i want it to be a nice overview of everything else on the site. 

but for now, it should include:
- [x] navigation to other pages
- [x] brief description of the site, i guess
- [x] link to mastodon
- [x] link to jillian.cloud
- [x] link to jillian.garden

## tasks
- [x] add page to /src
- [x] decide what content should go on the page
- [x] figure out basic page layout
- [x] write & add draft content
