### ISSUE TITLE
[new page] /blog

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/oolong#5]
## page details
**title:** blog
**url:** /blog

## page content
this page will eventually show a collection of blog posts — for now, i just want to get it set up with:
- [ ] a header
- [ ] a link to one [sample blog post](https://jillian.garden/122923)
  - [ ] blog post title
  - [ ] blog post summary
  - [ ] date published

## tasks
- [ ] add page to /src
- [ ] decide what content should go on the page
- [ ] figure out basic page layout
- [ ] write & add draft content
