### ISSUE TITLE
add games to cms

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/oolong#61]
## tasks
- [ ] remove the existing games pages (have to recreate them in the cms)
- [ ] add `games` → `playing` folders to cms
- [ ] add a few current games to the `playing` folder
  - [ ] genshin
  - [ ] hsr
  - [ ] ffxiv
- [ ] add some content to the pages

### genshin
- [ ] link to [enka.network](https://enka.network/u/jillian/) profile
- [ ] latest spiral abyss results
- [ ] stats photo
- [ ] links to tools i've built
- [ ] link to lore site
- [ ] list of blog posts tagged with "genshin"

### hsr
- [ ] link to [enka.network](https://enka.network/u/jillian/) profile

### ffxiv
- [ ] [link to profile](https://na.finalfantasyxiv.com/lodestone/character/46218413/)
- [ ] [current progress in msq](https://ffxiv-progress.com/)
