### ISSUE TITLE
[new collection] books

### ISSUE THREAD

**Issue by jilliangmeehan** [jilliangmeehan/oolong#9]
## collection details
a collection of books i'm reading, have read, or want to read. eventually, maybe this connects with my literal bookshelf somehow, but for now i'll keep it simple.

**collection name:** books
**collection properties:**
- tags: book
- book details
  - title
  - author
  - cover
  - url (link to literal)
- status
  - want to read
  - reading
  - finished reading
  - abandoned
- rating (just use emoji for now, might use stars for literal later)
- notes (md body copy)

## tasks
- [x] make a **/books/** folder
- [ ] make a **book.md** layout with the above properties in the front matter
- [x] add a few books i'm currently reading to the collection

**Comment by jilliangmeehan** [comment]
didn't end up making a layout for this since i'm not sure it makes a ton of sense yet. also edited the properties a bit for simplicity's sake.
